### PR TITLE
28 feture create moderators acounts basiuk

### PR DESCRIPTION
**Pull request by DMTRIP**

### CODE REVIEW

**Review by Dmitry528 — COMMENTED** [review]
Change field is_admin:  on false, when you create moderators, at this moment we have --- is_admin: null

**Review by Dmitry528 — COMMENTED** [review]
Resolve conflicts in files ---  routes/admin-api.js

**Comment by DMTRIP** [comment]
> Resolve conflicts in files --- routes/admin-api.js

done

**Review by Dmitry528 — COMMENTED** [review]
Conflict in controllers/user-controller.js

**Review by Dmitry528 — APPROVED** [review]
It works good, i create post request with POSTMAN and send request to --- localhost:8080/admin/api/moderator/create, with  {
	"avatar": "TEST DCHEK",
	"name": "TEST DCHEK",
	"surname": "TEST DCHEK",
	"birth_date": "2005-05-05T21:00:00.000+00:00",
	"password": "qweqweqwe",
	"nickname": "DCHEK",
	"email": "HelloJapan@gmail.com"
}

and after this i create new moderator, Good Work

**Review by andrii-kondratiuk — APPROVED** [review]

**Review by marrybbb — APPROVED** [review]

**Review by Dmitry528 — COMMENTED** [review]
Another conflict in routes/api.js after todays pull-requests

**Pull request merged**
