### PR TITLE
20 feature login basiuk

### PR DESCRIPTION
**Pull request by DMTRIP**

### CODE REVIEW

**Review by victorpoliushko — COMMENTED** [review]
how to start your app?

**Comment by katemalash** [comment]
Please, don't make new commits to existing pull-request if they are not required by reviewers.

**Review by Viktor-Hordynskyi — APPROVED** [review]

**Review by AndriiDruzhytskyi — APPROVED** [review]
All works fine. Good job!

**Review by Viktor-Hordynskyi — APPROVED** [review]

**Review by victorpoliushko — APPROVED** [review]
works good

**Pull request merged**
