### PR TITLE
15 feature postgres init poliushko

### PR DESCRIPTION
**Pull request by victorpoliushko**
Who knows how associations works in sequelize please check it in my code.
**Paste that in .env file for correct connection**
sqlDataBase='postgres'
sqlPassword='postgres'
host=35.238.91.116
sqlPort=5432

### CODE REVIEW

**Review by DMTRIP — APPROVED** [review]

**Review by innomaxx — COMMENTED** [review]
1) Why all endpoints in separate files instead routes grouping by entity type?
2) Why `exports` instead of `module.exports`?

**Review by innomaxx — APPROVED** [review]

**Comment by DMTRIP** [comment]
Please make **exports** from your models files like this at the end of your file type module.exports = yourModelName (User for instance) otherwise when you require your model you get nothing . 
Everything else works correctly **✓**

**Review by Dmitry528 — COMMENTED** [review]
1) Delete all require models in App.js
2) Create module.export = "Your model name" on all models

**Comment by victorpoliushko** [comment]
> 1. Why all endpoints in separate files instead routes grouping by entity type?
> 2. Why `exports` instead of `module.exports`?
1. Don't understand the question.
2. Don't see the difference here.

**Comment by victorpoliushko** [comment]
> 1. Delete all require models in App.js
> 2. Create module.export = "Your model name" on all models

Ok, give me my pull request back)

**Comment by innomaxx** [comment]
Push new commit with changes, it will be added to this pull request 👍

**Review by Dmitry528 — APPROVED** [review]

**Pull request merged**
